const photos = [
  {
    id: 1,
    src: "https://picsum.photos/seed/yg01/600/400",
    title: "开营仪式",
    desc: "仪光赤心实践队2026寒假社会实践正式启动，队员们在红色横幅前合影，满怀激情地开始了这段意义非凡的旅程。",
    tag: "实践活动",
    date: "2026-01-15",
    location: "福州大学",
  },
  {
    id: 2,
    src: "https://picsum.photos/seed/yg02/600/400",
    title: "参观革命纪念馆",
    desc: "队员们参观福建省革命历史纪念馆，聆听讲解员讲述革命先烈的英勇事迹，深刻感受红色精神的伟大力量。",
    tag: "红色教育",
    date: "2026-01-16",
    location: "福建革命历史纪念馆",
  },
  {
    id: 3,
    src: "https://picsum.photos/seed/yg03/600/400",
    title: "团队讨论",
    desc: "队员们围坐在一起，热烈讨论当天的实践心得，每个人都有不同的感悟和收获。",
    tag: "团队风采",
    date: "2026-01-16",
    location: "实践基地",
  },
  {
    id: 4,
    src: "https://picsum.photos/seed/yg04/600/400",
    title: "社区志愿服务",
    desc: '走进社区，为当地居民提供志愿服务，用实际行动践行"为人民服务"的红色精神。',
    tag: "社区服务",
    date: "2026-01-17",
    location: "鼓楼区社区",
  },
  {
    id: 5,
    src: "https://picsum.photos/seed/yg05/600/400",
    title: "重走红色路线",
    desc: "沿着先辈们曾经走过的道路前行，每一步都踏在历史的印记上，感受革命年代的艰苦与伟大。",
    tag: "红色教育",
    date: "2026-01-17",
    location: "古田会议旧址",
  },
  {
    id: 6,
    src: "https://picsum.photos/seed/yg06/600/400",
    title: "夜间学习研讨",
    desc: "夜晚的灯光下，队员们认真研读红色经典文献，讨论新时代青年如何传承红色基因。",
    tag: "团队风采",
    date: "2026-01-18",
    location: "住宿基地",
  },
  {
    id: 7,
    src: "https://picsum.photos/seed/yg07/600/400",
    title: "采访革命后代",
    desc: "与革命先辈的后代面对面交流，听他们讲述父辈的故事，那些课本外的真实历史令人动容。",
    tag: "红色教育",
    date: "2026-01-18",
    location: "福州市区",
  },
  {
    id: 8,
    src: "https://picsum.photos/seed/yg08/600/400",
    title: "集体合影",
    desc: "在纪念碑前的庄重合影，每位队员脸上都写满了坚定与自豪，这是属于我们的红色记忆。",
    tag: "团队风采",
    date: "2026-01-19",
    location: "烈士陵园",
  },
  {
    id: 9,
    src: "https://picsum.photos/seed/yg09/600/400",
    title: "关爱老人活动",
    desc: "走访当地敬老院，陪伴老人们聊天、表演节目，用温暖传递爱心，践行红色志愿精神。",
    tag: "社区服务",
    date: "2026-01-19",
    location: "福州敬老院",
  },
  {
    id: 10,
    src: "https://picsum.photos/seed/yg10/600/400",
    title: "红色主题宣讲",
    desc: "在社区广场开展红色主题宣讲活动，向居民们介绍革命历史，传播红色文化。",
    tag: "实践活动",
    date: "2026-01-20",
    location: "社区广场",
  },
  {
    id: 11,
    src: "https://picsum.photos/seed/yg11/600/400",
    title: "图书捐赠仪式",
    desc: "向山区小学捐赠红色读物和学习用品，希望在孩子们心中种下红色的种子。",
    tag: "社区服务",
    date: "2026-01-20",
    location: "山区小学",
  },
  {
    id: 12,
    src: "https://picsum.photos/seed/yg12/600/400",
    title: "参观林则徐纪念馆",
    desc: '走进林则徐纪念馆，感受"苟利国家生死以"的爱国情怀，学习先贤的高尚品格。',
    tag: "红色教育",
    date: "2026-01-20",
    location: "林则徐纪念馆",
  },
  {
    id: 13,
    src: "https://picsum.photos/seed/yg13/600/400",
    title: "实践日记分享",
    desc: "队员们在营地分享各自的实践日记，字里行间流露出对红色文化的深刻理解和真挚情感。",
    tag: "团队风采",
    date: "2026-01-21",
    location: "实践基地",
  },
  {
    id: 14,
    src: "https://picsum.photos/seed/yg14/600/400",
    title: "清晨晨跑",
    desc: "清晨的第一缕阳光中，队员们沿着红色长廊慢跑，用朝气蓬勃的姿态迎接新一天的实践。",
    tag: "团队风采",
    date: "2026-01-21",
    location: "实践基地",
  },
  {
    id: 15,
    src: "https://picsum.photos/seed/yg15/600/400",
    title: "手绘红色地图",
    desc: "队员们合作手绘福建红色文化地图，标注每一个革命遗址，记录我们走过的红色足迹。",
    tag: "实践活动",
    date: "2026-01-21",
    location: "实践基地",
  },
  {
    id: 16,
    src: "https://picsum.photos/seed/yg16/600/400",
    title: "瞻仰烈士纪念碑",
    desc: "全体队员在烈士纪念碑前默哀致敬，缅怀为国捐躯的英烈们，铭记历史，砥砺前行。",
    tag: "红色教育",
    date: "2026-01-22",
    location: "烈士纪念碑",
  },
  {
    id: 17,
    src: "https://picsum.photos/seed/yg17/600/400",
    title: "社区环保行动",
    desc: "结合红色精神与环保理念，队员们在社区开展环境清洁活动，以实际行动美化家园。",
    tag: "社区服务",
    date: "2026-01-22",
    location: "社区街道",
  },
  {
    id: 18,
    src: "https://picsum.photos/seed/yg18/600/400",
    title: "制作宣传视频",
    desc: "利用拍摄的素材制作红色文化宣传短片，用新媒体方式让更多年轻人了解红色历史。",
    tag: "实践活动",
    date: "2026-01-22",
    location: "实践基地",
  },
  {
    id: 19,
    src: "https://picsum.photos/seed/yg19/600/400",
    title: "红色故事会",
    desc: "篝火旁的红色故事会，每位队员讲述一个革命故事，火光映照下的面孔格外动人。",
    tag: "实践活动",
    date: "2026-01-23",
    location: "营地",
  },
  {
    id: 20,
    src: "https://picsum.photos/seed/yg20/600/400",
    title: "调研走访",
    desc: "深入基层走访调研，了解当地红色文化保护现状，为传承红色基因献计献策。",
    tag: "实践活动",
    date: "2026-01-23",
    location: "乡镇街道",
  },
  {
    id: 21,
    src: "https://picsum.photos/seed/yg21/600/400",
    title: "书法展示",
    desc: "队员们用书法书写红色诗词和革命名言，一笔一划间流淌着对先辈的敬仰之情。",
    tag: "红色教育",
    date: "2026-01-23",
    location: "文化中心",
  },
  {
    id: 22,
    src: "https://picsum.photos/seed/yg22/600/400",
    title: "趣味运动会",
    desc: "实践之余的趣味运动会，拔河、接力跑，队员们在欢笑中增进了团队凝聚力。",
    tag: "团队风采",
    date: "2026-01-24",
    location: "运动场",
  },
  {
    id: 23,
    src: "https://picsum.photos/seed/yg23/600/400",
    title: "总结大会",
    desc: "实践活动圆满收官，队员们在总结大会上分享收获与感悟，这段经历将成为珍贵的记忆。",
    tag: "实践活动",
    date: "2026-01-24",
    location: "福州大学",
  },
  {
    id: 24,
    src: "https://picsum.photos/seed/yg24/600/400",
    title: "告别与展望",
    desc: "寒假实践虽然结束，但红色精神的传承永不停歇。期待下次再聚，继续仪光赤心的使命。",
    tag: "团队风采",
    date: "2026-01-24",
    location: "福州大学",
  },
];
